### ISSUE TITLE
error while convert swagger.json to api.yaml

### ISSUE THREAD

**Issue by raccoon-mh** [cloud-barista/cm-mayfly#13]
M-CMP / mc-iam-manager [링크](https://m-cmp.github.io/mc-iam-manager/swagger/)

위 swagger 문서를 mayfly 의 api tool 을 이요하여 api.yaml 생성시

json unmarshal error 가 발생하는 것을 발견했습니다.

관련하여. 도움 또는 버그 픽스를 하실 수 있는지 이슈 남겨드립니다. :)

**Comment by MZC-CSC** [comment]
현재 tool 서브 명령은 api.yaml 파일 작성을 보조하기 위해 임의로 지원되는 기능으로서...
아직은 모든 Swagger JSON 문법을 지원하지는 않기 때문에 지원되지 않는 파일이 존재합니다.
정보 제공 감사드리며 해당 파일의 형태도 지원될 수 있도록 고려해 보겠습니다.

**Comment by MZC-CSC** [comment]
분석 결과 https://swagger.io/docs/specification/describing-parameters/ 스펙 기준으로 보통은 GET / POST 등의 Method 하위에 parameters 정보가 오는데 요청하신 swagger 문서의 경우 GET/POST 등의 Method가 정의되는 부분에 Method가 아닌 parameters 정보가 서술되어서 발생하는 현상입니다.
전체 Method가 공통으로 사용하는 parameters를 정의하는 방식이 표준인지 모르겠지만...
요청하신 방식의 처리를 감안해서 Method 부분에 Method가 아닌 정의가 올 경우 무시하고 진행하도록 로직을 변경했습니다.
