### ISSUE TITLE
Swagger annotation item referenced when generating apicall's action name.

### ISSUE THREAD

**Issue by hippo-an** [cloud-barista/cm-mayfly#8]
각 프레임워크에서 제공하는 API 를 호출하기 위한 하위 커맨드를 정의하기 위해 CLI 에 등록할 각각의 API 의 이름이 필요합니다.

```shell
$ mayfly api <API name>
```
<br/>

이를 위해  각 프레임워크에서 제공하는 Swagger 를 기반으로 API 를 파악하고 있습니다.

현재 각 프레임워크에서 제공하는 Swagger 에서 API 이름으로 사용할 수 있는 항목은 Summary 와 Description 입니다.

```text
Summary
- 수행하는 작업에 대한 간략한 요약
Description
- 작업의 동작에 대한 자세한 설명
```

두 필드의 스펙상 mayfly 에서 사용하는 서브 커맨드로 변환하는 경우 의도치 않은 긴 이름을 야기합니다.
또한 통일된 규격으로 사용되고 있는 항목이 아니기 때문에 통일된 형태의 결과를 보장하지 못합니다.

**Comment by hippo-an** [comment]
[스웨거 공식 문서](https://swagger.io/docs/specification/paths-and-operations/) 에서 참고하여 작업 식별을 위해 사용하는 고유값인 OperationId 가 존재합니다.

명확한 사용 사례, 시스템 내 고유 값 등의 속성이 mayfly 에서 호출하기 위한 각각의 API 이름으로 사용하기에 적절해 보입니다.

- swaggo/swag 패키지를 사용하는 경우 다음과 같이 사용할 수 있습니다.
```go
// SomeMethod
// @Id			SomeMethod
// @Summary             Get price info from somewhere...
func SomeMethod() {
}
```
mayfly 에서 서브 커맨드로 변환하는 로직에서 OperationId 항목을 서브 커맨드의 이름으로 파싱할 수 있도록 서브 시스템에서 제공하는 swagger 문서에 해당 항목을 포함하는게 좋아 보입니다.

**Comment by innodreamer** [comment]
@hippo-an 일단 현재의 방법인 CLI 내부 기능으로 swagger 기반으로 프레임워크 각각의 API를 호출하는 방식은 좀 보류해주시는게 좋을거 같습니다.
다음 주 워크샵에서 현재 진행 사항들을 공유해주실때 이 CLI 개발 업무 내용도 포함해서 공유해주시면 좀더 논의해서 방향을 구체적으로 잡아 CLI를 어떤 용도로 사용하고 어떤 방식으로 개발을 진행할지 정하고 개발을 진행하면 좋을거 같습니다.

**Comment by hippo-an** [comment]
워크샵에서 논의한 내용을 바탕으로 정리한 내용입니다.
***
- CLI 내부 기능으로 각 프레임워크의 api 를 호출하는 방식은 일단 진행하도록 하겠습니다.

- 다만 1차 통합 이후 마이그레이션 플로우 확인을 통해,
  마이그레이션 기능을 수행하는 커맨드의 필요성 및 범위를 검토 후 
  개발 추진 여부에 대해 재논의가 진행될 예정입니다.

- OperationId 항목을 추가한 swagger.json 파일을 
  각 프레임워크의 root/api 폴더 하위에 제공하는 것으로 논의했습니다.
***

상기 내용에 따라 각 프레임워크의 swagger 문서에 OperationId 항목을 포함 부탁드립니다.

**Comment by yunkon-kim** [comment]
> * OperationId 항목을 추가한 swagger.json 파일을
>   각 프레임워크의 root/api 폴더 하위에 제공하는 것으로 논의했습니다.

위와 관련하여 살짝 오해가 있을 수 있어 첨언드립니다. 아래를 참고하시기 바랍니다.
- API docs (e.g., swagger docs)의 경로는 메인테이너가 결정 및 공유하고,
- 가능하다면 `root/api` 경로로 제공한다.

**Comment by hippo-an** [comment]
확인하였습니다.

감사합니다. :)

**Comment by seokho-son** [comment]
@hippo-an (cc @yunkon-kim @innodreamer)

- CB-Tumblebug에 https://github.com/cloud-barista/cb-tumblebug/issues/1594 를 진행하고
- 해당 문서가 포함된 버전 v0.8.13을 릴리스하였습니다. https://github.com/m-cmp/m-cmp/issues/7#issuecomment-2115193286

필요하신 정보가 맞는지 확인 부탁드립니다.

**Comment by hippo-an** [comment]
@seokho-son 
- CB-Tumblebug 의 v0.8.13 릴리즈 버전에 operationId 항목 추가된 것 확인했습니다.([링크](https://raw.githubusercontent.com/cloud-barista/cb-tumblebug/v0.8.13/src/api/rest/docs/swagger.json))
- api.yaml 을 생성하기 위한 swagger 문서의 필요 정보가 맞습니다.
- 감사합니다 :)
