### ISSUE TITLE
Definition of an API that can check the status of the subsystem

### ISSUE THREAD

**Issue by hippo-an** [cloud-barista/cm-mayfly#9]
- 각 프레임워크의 애플리케이션 레벨의 상태를 확인할 수 있는 api 정의가 필요합니다.
- 해당 api 는 cli 를 통한 서브 시스템 실행 시 상태 확인 용도로 사용될 수 있습니다.
- 추가로 공통된 api 엔드포인트를 가지면 좋을 것 같습니다.

**Comment by seokho-son** [comment]
안녕하세요. @hippo-an 

언급하신 애플리케이션 레벨의 상태 의미는

시스템에 API로 접속 가능 여부와 
시스템 기능 구동에 문제가 없는지 여부를 의미하시는 것이 맞을까요? ^^

**Comment by hippo-an** [comment]
안녕하세요 :) @seokho-son 

표현이 모호했다면 죄송합니다.

말씀하신 **API 접속 가능 여부와 시스템 기능에 문제가 없는지 확인 여부** 의 의미로 사용한 것이 맞습니다.

**Comment by seokho-son** [comment]
@hippo-an 확인 감사합니다. :)

아래와 같이 추진 예정입니다. 혹시 더 좋은 아이디어가 있으신지, 공지 전에 한번 살펴봐주실 수 있으실까요? 

- https://github.com/cloud-barista/cb-tumblebug/discussions/1524

**Comment by hippo-an** [comment]
답변 감사합니다.
- Discussions 확인했으며 이견 없습니다.
